//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDTU_IT_alumni_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumnus()
        {
            this.Notifies = new HashSet<Notify>();
        }
    
        public string IDAlumni { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string HomeTown { get; set; }
        public string PersonalWebsite { get; set; }
        public string GraduationType { get; set; }
        public string Majors { get; set; }
        public int GraduationYear { get; set; }
        public string CurrentCompany { get; set; }
        public string AcademicLevel { get; set; }
        public System.DateTime TimeToCompletionOfThesisDefense { get; set; }
        public string UsersName { get; set; }
        public System.DateTime jobBeginDate { get; set; }
        public string skill { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notify> Notifies { get; set; }
    }
}
