//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDTU_IT_alumni_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuuHSSV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuuHSSV()
        {
            this.ThongBaos = new HashSet<ThongBao>();
        }
    
        public string IDHSSV { get; set; }
        public string Ten { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string QuocTich { get; set; }
        public string QueQuan { get; set; }
        public string CaNhan { get; set; }
        public string XepLoaiTotNghiep { get; set; }
        public string NganhHoc { get; set; }
        public int NamTotNghiep { get; set; }
        public string CongTyHienTai { get; set; }
        public string HocVanCaoHoc { get; set; }
        public System.DateTime ThoiGianHoanThanhBaoVeLuanAn { get; set; }
        public string TenTaiKhoan { get; set; }
        public System.DateTime jobBeginDate { get; set; }
        public string workplace { get; set; }
        public string skill { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
    }
}
