//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDTU_IT_alumni_management_system.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TDTUAlumnisManagementSystemEntities : DbContext
    {
        public TDTUAlumnisManagementSystemEntities()
            : base("name=TDTUAlumnisManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Alumnus> Alumni { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<ChatBot> ChatBots { get; set; }
        public virtual DbSet<Enterprise> Enterprises { get; set; }
        public virtual DbSet<GraduationInfo> GraduationInfoes { get; set; }
        public virtual DbSet<Header> Headers { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Notify> Notifies { get; set; }
        public virtual DbSet<RecruitmentNew> RecruitmentNews { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    }
}
